env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
    "no-shadow": ["error", { "builtinGlobals": false, "hoist": "never", "allow": [] }]
}
