import Joi from 'joi';

export const postSchema = Joi.object({
  atende_convenio: Joi.boolean(),
  atende_particular: Joi.boolean(),
  atende_publico: Joi.boolean(),
  ativo: Joi.boolean(),
  bairro: Joi.string().allow('', null).required(),
  celular: Joi.string().allow('', null).required(),
  cidade: Joi.string().allow('', null).required(),
  codigo_postal: Joi.string().allow('', null).required(),
  complemento: Joi.string().allow('', null),
  cpf: Joi.string().allow('', null),
  passaporte: Joi.string().allow('', null),
  dados_complementares: Joi.any(),
  data_nascimento: Joi.string().allow('', null).required(),
  email: Joi.string().email().required().messages({'string.email': '{{#label}} Tipo de email inválido'}),
  endereco: Joi.string().allow('', null).required(),
  estado_civil: Joi.string().allow('', null).required(),
  nome: Joi.string().allow('', null).required(),
  numero: Joi.string().allow('', null),
  perfil_acesso: Joi.string().allow('', null).required(),
  rg: Joi.string().allow('', null).required(),
  senha: Joi.string().allow('', null).required(),
  sexo: Joi.string().allow('', null).required(),
  sobre: Joi.string().allow('', null),
  telefone: Joi.string().allow('', null).required(),
  titulo: Joi.string().allow('', null),
  uf: Joi.string().allow('', null).required(),
  url_imagem: Joi.string().allow('', null),
});

export const patchSchema = Joi.object({
  atende_convenio: Joi.boolean(),
  atende_particular: Joi.boolean(),
  atende_publico: Joi.boolean(),
  ativo: Joi.boolean(),
  bairro: Joi.string().allow('', null),
  celular: Joi.string().allow('', null),
  cidade: Joi.string().allow('', null),
  codigo_postal: Joi.string().allow('', null),
  complemento: Joi.string().allow('', null),
  cpf: Joi.string().allow('', null),
  passaporte: Joi.string().allow('', null),
  dados_complementares: Joi.any(),
  data_nascimento: Joi.string().allow('', null),
  email: Joi.string().email(),
  endereco: Joi.string().allow('', null),
  estado_civil: Joi.string().allow('', null),
  id_ambiente: Joi.string().allow('', null),
  nome: Joi.string().allow('', null),
  numero: Joi.string().allow('', null),
  perfil_acesso: Joi.string().allow('', null),
  rg: Joi.string().allow('', null),
  senha: Joi.string().allow('', null),
  sexo: Joi.string().allow('', null),
  sobre: Joi.string().allow('', null),
  telefone: Joi.string().allow('', null),
  titulo: Joi.string().allow('', null),
  uf: Joi.string().allow('', null).required(),
  url_imagem: Joi.string().allow('', null),
});
